Repository denysdovhan/wtfjs, pull requests merged in 2020-10, with the labels that each got.

#149 Brazilian Portuguese translation
  README-pt-br.md
  README.md
Labels: improvement

#153 Update README-zh-cn.md
  README-zh-cn.md
Labels: typo

#114 Fix output of `new f()`
  README.md
Labels: typo

#122 true() is not a function
  README.md
Labels: typo

#119 Add "resolve() won't return Promise instance"
  README-zh-cn.md
  README.md
Labels: proposal

#157 Polish translation
  README-pl-pl.md
  README.md
Labels: help wanted, translation
