Repository denysdovhan/wtfjs, pull requests merged in 2021-02, with the labels that each got.

#179 Fix outdated links to Abstract Equality Comparison reference
  README.md
Labels: bug

#176 Revert some formatting and errors in example code
  .github/FUNDING.yaml
  .github/workflows/release.yml
  README-it-it.md
  README-pl-pl.md
  README-pt-br.md
  README-zh-cn.md
  README.md
  package-lock.json
  package.json
Labels: typo

#180 Added special cases comparing Object.is and ===
  README.md
Labels: proposal

#152 Hindi translation
  README-hi.md
  README.md
Labels: help wanted, translation

#102 Continuation of "function is not a function" bug
  README.md
Labels: new-example

#130 Sinhala translation
  README-si.md
Labels: help wanted, translation

#200 Fixed typo: "agruments" to "arguments"
  README.md
Labels: typo
