Repository denysdovhan/wtfjs, pull requests merged in 2021-06, with the labels that each got.

#203 fix typo
  README.md
Labels: typo

#205 Fix grammatical issues from Korean translation
  README-kr.md
Labels: translation, typo

#206 Fixes issues with some wtfs
  README.md
Labels: typo

#210 A setTimeout object
  README.md
Labels: new-example
